name: KMS Server Sync

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日 00:00 UTC 触发
  workflow_dispatch: # 添加 workflow_dispatch 触发器
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'info'
        type: choice
        options:
        - info
        - debug
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch cloudflare

      - name: Run KMS sync script
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          DNS_RECORD_NAME: kms.everyhub.top # 替换为你的 DNS 记录名称
        run: node kms-sync.js
